version: '3.3'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8383:80
    networks:
      - network
    #  FOR PRODUCTION THIS PART NEEDS TO BE OMITTED
    volumes:
      - ./:/var/www/html

networks:
  network:
    driver: bridge